@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package redcrafter07.processed.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;