@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package redcrafter07.processed.gui.widgets;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;