@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package redcrafter07.processed.gui.inventory;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;