@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package redcrafter07.processed.block.tile_entities.capabilities;

import com.mojang.blaze3d.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;