@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package redcrafter07.processed.block.machine_abstractions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;