modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "${kff_version_range}" # Require at least 4.x
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
# optional
#credits="The ExampleMod dev team"
authors = "${mod_authors}"
description = '''${mod_description}'''
displayURL = "https://modrinth.com/project/processed"
logoFile = "logo.png"
# TODO: Updates
# See: https://docs.modrinth.com/#tag/misc/operation/forgeUpdates
# updateJSONURL=""

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "jade"
type = "optional"
ordering = "AFTER"
[[dependencies.${mod_id}]]
modId = "emi"
type = "optional"